version: '3.8'

services:
  testcontainers_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONFIGURATION=Release
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=my_db;Username=my_user;Password=my_password
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    user: "${APP_UID:-1000}"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
